### ISSUE TITLE
Pin namings

### ISSUE THREAD

**Issue by Stredoslovak** [deividAlfa/ST7789-STM32-uGUI#2]
I am having some problems regarding the PIN_DEFFINITONs. Mainly the DC and RST pins. I don't know what you meant by "CUBEmx pin names", I've tried defining as PAx and also numbers.
None of this works.
Could you please provide me with a configured LCD.h file? So I can figure out the names?

Here is a part of my current LCD.h setup:
```
/* Pin connections. Use same names as in CubeMX */
#define LCD_DC 11
#define LCD_RST	12
//#define LCD_CS                LCD_CS  
//#define LCD_BL              LCD_BL
```
EDIT
I've managed to advance by using this:
```
/* Pin connections. Use same names as in CubeMX */
#define LCD_DC GPIO_PIN_11
#define LCD_RST	GPIO_PIN_12
//#define LCD_CS                LCD_CS  /* Disable if your display has no CS pin */
//#define LCD_BL              LCD_BL  /* Enable if you need backlight control */
```
But it still does not compile correctly. What am I missing?

This is the error message that I am getting:
```expected ')' before '_GPIO_Port'```

**Comment by Stredoslovak** [comment]
Also, where should I define the GPIO port that I am using?
I've been doing it in a `lcd.h` file. By adding the `GPIOA` in front of the `_GPIO_Port` as follows
```
#define LCD_PIN(pin, out) ( LCD_CON(pin,GPIOA_GPIO_Port->BSRR) = (out ? LCD_CON(pin,_Pin) : LCD_CON(pin,_Pin)<<16 ))
```

**Comment by Stredoslovak** [comment]
Just please send me a configured `lcd.h` file.

**Comment by deividAlfa** [comment]
Basic C syntax mistake, "-" is for  subtracting, always use "_”.
LCD-CS means "LCD minus CS".

**Comment by Stredoslovak** [comment]
> Basic C syntax mistake, "-" is for subtracting, always use "_”. LCD-CS means "LCD minus CS".

Great, thanks for this, but I've figured that out already. Instead I now have a much bigger problem. It's unrelated to the original topic. So I'll create a new issue.

**Comment by deividAlfa** [comment]
You have not one, but 3 complete working examples, look the ST7789_demo_xxx folders!
These are fully working projects, import any in CubeIDE and you'll see how it's made.
