### ISSUE TITLE
ST7789_demo_f407ve failed compilation

### ISSUE THREAD

**Issue by guilherme-escuissato** [deividAlfa/ST7789-STM32-uGUI#4]
I just tested the compilation of the 3 demos. Both the ST7789_demo_f103c8 and ST7789_demo_f411ce built without problems. However, ST7789_demo_f407ve presented this warning:

![image](https://github.com/deividAlfa/ST7789-STM32-uGUI/assets/132772259/c9df57ca-9501-40af-afee-2a59197a15e5)

**Comment by deividAlfa** [comment]
Should be fixed now. The linker scripts were missing.
