### ISSUE TITLE
Display Fill doesn't work correctly on different display sizes

### ISSUE THREAD

**Issue by m1geo** [deividAlfa/ST7789-STM32-uGUI#5]
Changing `LCD_WIDTH` and `LCD_HEIGHT` as well as `LCD_X_SHIFT` and `LCD_X_SHIFT` doesn't work with all functions. The demo code's bouncing ball, uGUI test window, text display and drawing functions seem to work OK, as well as the image display.

However, the fill screen doesn't work.

Using a [Waveshare 2" LCD Module](https://www.waveshare.com/wiki/2inch_LCD_Module), 320x240, ST7789V controller.

**Comment by deividAlfa** [comment]
Yeah, the original code was made for smaller displays, so it used 16-bit variables in some places.
320*240=76800, so it would woverflow the variable and only draw 11K pixels.
Should be working now.

**Comment by m1geo** [comment]
Thanks very much. Will give the latest a try!
